// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfwwfeljgkphohajwtkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmd3dmZWxqZ2twaG9oYWp3dGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxOTg2MzAsImV4cCI6MjA0OTc3NDYzMH0.BDPqxoCCsUdAEh8EkH2HFHnul_VzHitzge1vPTItjYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);